---
- name: Push the config to router
  hosts:
     - all
  roles:
    - juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no

    - name: password
      prompt: Junos Password
      private: Yes
  vars:
    tmp_dir: "/home/ansible/ansible/playbooks"
    conf_file: "{{ tmp_dir}}/configuration_file.set"

  tasks:
    - debug: var=tmp_dir
    - debug: var=conf_file

    - name: install configuration
      juniper_junos_config:
        host: "{{ inventory_hostname}}"
        user: "{{ username }}"
        passwd: "{{ password }}"
        src: "{{ conf_file }}"
        timeout: 120
        ignore_warning: true
        load: set
        comment: "Changed Configuration"
        format: text
       # confirm: 180
        check_commit_wait: 4
        check: true
        commit: true
      register: response
    - name: Print the response
      debug:
         var: response
